#### Pytorch Basics

In [ ]:
import torch

In [4]:
#Check if cuda is available in your machine
torch.cuda.is_available()

True

In [5]:
#Initializing Variables

#Tensor --> Array

x = torch.Tensor([1,2,3])
y = torch.Tensor([6,7,8])

print(x*y)

tensor([ 6., 14., 24.])


In [8]:
#Initialize a matrix full of Zero
X = torch.zeros([3,5])

In [9]:
print(X)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [10]:
X.shape

torch.Size([3, 5])

In [11]:
#Initialize a matrix full of Random Nos

w = torch.rand([3,5])

In [12]:
print(w)

tensor([[0.0869, 0.2370, 0.8204, 0.4249, 0.4368],
        [0.7619, 0.7957, 0.2893, 0.4270, 0.8530],
        [0.3625, 0.3624, 0.6619, 0.6068, 0.9263]])


In [13]:
w.shape

torch.Size([3, 5])

In [16]:
#To reshare an array

w = w.view([5,3])

In [17]:
w.shape

torch.Size([5, 3])